spring:
  application:
    name: springserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tave?createDatabaseIfNotExist=true
    username: root
    password: tkfkdgo2001!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    compatibility-verifier:
      enabled: false  # 이 부분을 추가하여 호환성 검사를 비활성화

  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: cHBpeW9ucHBpeW9uZw== # base64로 ppiyongppiyong 인코딩한 값
    access:
      expiration: 2592000000 # 60L * 60L * 24L * 30000
    refresh:
      expiration: 2592000000

aws-property:
  s3-bucket-name: ppiyongpiyong-bucket
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  aws-region: ap-northeast-2

kakao:
  api:
    key: 3c8be9670acb0426f12d1ad91ba1a063

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

