spring:
  application:
    name: springserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tave?createDatabaseIfNotExist=true
    username: root
    password: tkfkdgo2001!
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
aws-property:
  s3-bucket-name: ppiyongpiyong-bucket
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  aws-region: ap-northeast-2
