name: CD

on:
  push:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: ppiyong

permissions:
  contents: read

jobs:
  build:
    name: Code deployment
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: make application.yml
        run: |
          ## create application.yml
          mkdir -p ./springserver/src/main/resources
          cd ./springserver/src/main/resources
          touch ./application.yml
          echo "${{ secrets.CD_APPLICATION }}" >> ./application.yml
          cat ./application.yml
        shell: bash

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: |
          cp ./springserver/build/libs/*.jar ./deploy
          ls ./deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./ppiyong.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./ppiyong.zip s3://$S3_BUCKET_NAME/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name ppiyongppiyong \
            --deployment-group-name ppiyong_deploy \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=ppiyong.zip \
            --region ap-northeast-2